### ISSUE TITLE
Bump ws version for compatibility with Node 4.x and later

### ISSUE THREAD

**Issue by pdf** [andyet/json-rpc-ws#5]
The current version of `ws` pulls in some old deps that don't build with recent versions of Node.

**Comment by wraithgar** [comment]
enabled greenkeeper so we should stay current now, thanks

**Comment by pdf** [comment]
Thanks, possible to cut a new npm release?

**Comment by wraithgar** [comment]
You'd think I would have remembered that, dang. Sorry. I blame ... the solstice?

Published as `v1.0.2`

**Comment by pdf** [comment]
Hehe, thx @wraithgar - all looking good now.
